version: '3'

services:
  db:
    container_name: houseplants_server_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: houseplants_server
